import APackage, { ANativePackage } from "./un-package";

type CorePackage_T = APackage & {
    isCore: true;
    isEngine: false;
    isNative: false;
};

type EnginePackage_T = APackage & {
    isCore: false;
    isEngine: true;
    isNative: false;
};

type NativeEngineTypes_T =
    | "Material"
    | "Modifier"
    | "TexModifer"
    | "StaticMeshMaterial"
    | "Font"
    | "Palette"
    | "Sound"
    | "Music"
    | "Primitive"
    | "Mesh"
    | "MeshAnimation"
    | "TerrainSector"
    | "TerrainPrimitive"
    | "LodMesh"
    | "StaticMesh"
    | "SkeletalMesh"
    | "Animation"
    | "ConvexVolume"
    | "MeshInstance"
    | "LodMeshInstance"
    | "SkeletalMeshInstance"
    | "StaticMeshInstance"
    | "Model"
    | "LevelBase"
    | "Level"
    | "LevelSummary"
    | "Polys"
    | "BspNodes"
    | "BspSurfs"
    | "Vectors"
    | "Verts"
    | "Texture"
    | "FractalTexture"
    | "FireTexture"
    | "IceTexture"
    | "WaterTexture"
    | "WaveTexture"
    | "WetTexture"
    | "ScriptedTexture"
    | "Client"
    | "Viewport"
    | "Canvas"
    | "Console"
    | "Player"
    | "NetConnection"
    | "DemoRecConnection"
    | "PendingLevel"
    | "NetPendingLevel"
    | "DemoPlayPendingLevel"
    | "Channel"
    | "ControlChannel"
    | "ActorChannel"
    | "FileChannel"
    | "Actor"
    | "Light"
    | "Inventory"
    | "Weapon"
    | "NavigationPoint"
    | "LiftExit"
    | "LiftCenter"
    | "WarpZoneMarker"
    | "InventorySpot"
    | "TriggerMarker"
    | "ButtonMarker"
    | "PlayerStart"
    | "Teleporter"
    | "PathNode"
    | "Decoration"
    | "Carcass"
    | "Projectile"
    | "Keypoint"
    | "locationid"
    | "InterpolationPoint"
    | "Triggers"
    | "Trigger"
    | "HUD"
    | "Menu"
    | "Info"
    | "Mutator"
    | "GameInfo"
    | "ZoneInfo"
    | "LevelInfo"
    | "WarpZoneInfo"
    | "SkyZoneInfo"
    | "SavedMove"
    | "ReplicationInfo"
    | "PlayerReplicationInfo"
    | "GameReplicationInfo"
    | "InternetInfo"
    | "StatLog"
    | "StatLogFile"
    | "Decal"
    | "SpawnNotify"
    | "Brush"
    | "Mover"
    | "Pawn"
    | "Scout"
    | "PlayerPawn"
    | "Camera"
    | "Bitmap";

type NativeCoreTypes_T =
    | "Object"
    | "Field"
    | "Const"
    | "Enum"
    | "Struct"
    | "Function"
    | "State"
    | "Class"
    | "TextBuffer"
    | "Property"
    | import("./un-property/un-property-types").PropertyTypes_T;

type NativeTypes_T =
    | NativeCoreTypes_T
    | NativeEngineTypes_T
    | "FinalBlend"
    | "StaticMesh"
    | "Shader"
    | "TerrainSector"
    | "PhysicsVolume"
    | "Model"
    | "AmbientSoundObject"
    | "TerrainInfo"
    | "StaticMeshActor"
    | "WaterVolume"
    | "Emitter"
    | "MusicVolume"
    | "BlockingVolume"
    | "FadeColor"
    | "StaticMeshInstance"
    | "TexRotator"
    | "TexPanner"
    | "TexCoordSource"
    | "ColorModifier"
    | "TexOscillator"
    | "DefaultPhysicsVolume"
    | "TexEnvMap"
    | "Cubemap"
    | "MeshAnimation"
    | "MeshEmitter"
    | "SpriteEmitter"
    | "BeamEmitter"
    | "Projector"
    | "AntiPortalActor"
    | "AmbientSound";

type PackageConstructor_T<T extends APackage = APackage> = new (loader: import("../asset-loader").AAssetLoader, downloadPath: string) => T;
type CorePackageConstructor_T<T extends CorePackage_T = CorePackage_T> = new (loader: import("../asset-loader").AAssetLoader, downloadPath: string) => T;
type EnginePackageConstructor_T<T extends EnginePackage_T = EnginePackage_T> = new (loader: import("../asset-loader").AAssetLoader, downloadPath: string) => T;
type NativePackageConstructor_T<T extends ANativePackage = ANativePackage> = new (loader: import("../asset-loader").AAssetLoader) => T;

export type { CorePackage_T, EnginePackage_T, NativeEngineTypes_T, NativeCoreTypes_T, NativeTypes_T, PackageConstructor_T, CorePackageConstructor_T, EnginePackageConstructor_T, NativePackageConstructor_T };
